"""
Energy-Based Model with Contrastive Divergence training.

Reference: Du & Mordatch, "Implicit Generation and Modeling with Energy-Based
Models", NeurIPS 2019.

Training: Contrastive divergence — push energy down on real data, up on
    negatives generated by short-run Langevin MCMC. A replay buffer stores
    recent negatives for training stability.

Sampling: Langevin MCMC — x <- x - (step/2) * grad_x E(x) + sqrt(step) * z.
"""
from typing import Optional

import torch
import torch.nn as nn


class EBM:
    """Energy-Based Model with contrastive divergence training.

    Args:
        cd_steps: Number of Langevin MCMC steps for generating negatives during training.
        cd_step_size: Step size for training MCMC.
        buffer_size: Size of the replay buffer.
        reinit_freq: Fraction of negatives initialized from noise (vs buffer).
        energy_reg: Regularization coefficient on energy magnitudes.
        langevin_steps: Number of Langevin steps for sampling (inference).
        langevin_step_size: Step size for sampling Langevin dynamics.
    """

    def __init__(
        self,
        cd_steps: int = 60,
        cd_step_size: float = 0.01,
        cd_data_init: bool = False,
        cd_noise_std: float = 0.3,
        cd_noise_scale: float = 1.0,
        buffer_size: int = 10000,
        reinit_freq: float = 0.05,
        energy_reg: float = 0.001,
        langevin_steps: int = 1000,
        langevin_step_size: float = 0.01,
        langevin_grad_clip: float = 0.0,
        langevin_clamp: float = 0.0,
        langevin_noise_scale: float = 1.0,
        langevin_anneal: bool = False,
        langevin_noise_end: float = 0.01,
    ):
        self.cd_steps = cd_steps
        self.cd_step_size = cd_step_size
        self.cd_data_init = cd_data_init  # init CD chains from data+noise instead of buffer
        self.cd_noise_std = cd_noise_std  # noise std when using data-initialized CD
        self.cd_noise_scale = cd_noise_scale  # noise multiplier for training MCMC (1.0=standard, <1=gradient-dominated)
        self.buffer_size = buffer_size
        self.reinit_freq = reinit_freq
        self.energy_reg = energy_reg
        self.langevin_steps = langevin_steps
        self.langevin_step_size = langevin_step_size
        self.langevin_grad_clip = langevin_grad_clip  # max gradient norm per sample (0=disabled)
        self.langevin_clamp = langevin_clamp  # clamp sample coordinates (0=disabled)
        self.langevin_noise_scale = langevin_noise_scale  # multiplier on Langevin noise (0=gradient descent, 1=standard)
        self.langevin_anneal = langevin_anneal  # anneal noise from langevin_noise_scale to langevin_noise_end
        self.langevin_noise_end = langevin_noise_end  # final noise multiplier when annealing

        # Replay buffer (initialized lazily on first use)
        self._buffer = None
        self._buffer_idx = 0

    def _init_buffer(self, dim: int, device: torch.device):
        """Initialize replay buffer with random noise."""
        self._buffer = torch.randn(self.buffer_size, dim, device=device)

    def _sample_from_buffer(self, batch_size: int, device: torch.device, dim: int):
        """Sample initial points: mix of buffer samples and fresh noise."""
        if self._buffer is None:
            self._init_buffer(dim, device)

        n_reinit = int(batch_size * self.reinit_freq)
        n_buffer = batch_size - n_reinit

        # Sample from buffer
        indices = torch.randint(0, self.buffer_size, (n_buffer,), device=device)
        buffer_samples = self._buffer[indices].clone()

        # Fresh noise
        noise_samples = torch.randn(n_reinit, dim, device=device)

        return torch.cat([buffer_samples, noise_samples], dim=0)

    def _update_buffer(self, samples: torch.Tensor):
        """Update replay buffer with new negative samples."""
        if self._buffer is None:
            self._init_buffer(samples.shape[1], samples.device)
        n = samples.shape[0]
        if self._buffer_idx + n <= self.buffer_size:
            self._buffer[self._buffer_idx : self._buffer_idx + n] = samples.detach()
            self._buffer_idx = (self._buffer_idx + n) % self.buffer_size
        else:
            # Wrap around
            remaining = self.buffer_size - self._buffer_idx
            self._buffer[self._buffer_idx :] = samples[:remaining].detach()
            overflow = n - remaining
            self._buffer[:overflow] = samples[remaining:].detach()
            self._buffer_idx = overflow

    def _langevin_mcmc(
        self, model: nn.Module, x: torch.Tensor, steps: int, step_size: float,
        noise_scale_mult: float = 1.0, noise_end_mult: float = -1.0,
    ):
        """Run Langevin MCMC to generate samples.

        x <- x - (step_size/2) * grad_x E(x) + noise_mult * sqrt(step_size) * z

        Args:
            model: Energy function E(x) -> (B,).
            x: Initial points (B, D).
            steps: Number of MCMC steps.
            step_size: Langevin step size.
            noise_scale_mult: Multiplier on noise (1.0=standard, 0.0=gradient descent).
            noise_end_mult: If >= 0, linearly anneal noise from noise_scale_mult
                to noise_end_mult over the MCMC steps. If < 0, use constant noise.

        Returns:
            Updated samples (B, D).
        """
        x = x.detach().requires_grad_(True)
        anneal = noise_end_mult >= 0.0
        step_size_sqrt = step_size ** 0.5

        for i in range(steps):
            energy = model(x).sum()
            grad_x = torch.autograd.grad(energy, x)[0]

            # Clip gradient norm per sample to prevent exploding updates
            if self.langevin_grad_clip > 0:
                grad_norm = grad_x.norm(dim=-1, keepdim=True).clamp(min=1e-8)
                grad_x = grad_x * (self.langevin_grad_clip / grad_norm.clamp(min=self.langevin_grad_clip))

            # Compute noise scale (constant or annealed)
            if anneal:
                t = i / max(steps - 1, 1)
                current_mult = noise_scale_mult + t * (noise_end_mult - noise_scale_mult)
            else:
                current_mult = noise_scale_mult
            noise_scale = current_mult * step_size_sqrt

            x = x.detach() - (step_size / 2) * grad_x + noise_scale * torch.randn_like(x)

            # Clamp samples to prevent drift to infinity
            if self.langevin_clamp > 0:
                x = x.clamp(-self.langevin_clamp, self.langevin_clamp)

            x = x.requires_grad_(True)

        return x.detach()

    def sample_timesteps(self, batch_size: int, device: torch.device) -> torch.Tensor:
        """Return dummy timesteps (EBMs don't use timesteps)."""
        return torch.zeros(batch_size, device=device)

    def training_loss(
        self, model: nn.Module, x0: torch.Tensor, t: torch.Tensor, **kwargs
    ) -> torch.Tensor:
        """Contrastive divergence loss.

        L = E_data[E(x)] - E_neg[E(x_neg)] + reg * E[(E^2)]

        Pushes energy down on real data, up on negatives.

        Args:
            model: Energy network E(x) -> scalar energy (B,).
            x0: Real data samples (B, D).
            t: Ignored.
        """
        batch_size, dim = x0.shape
        device = x0.device

        # Energy on real data
        energy_real = model(x0)

        # Generate negatives via short-run Langevin MCMC
        if self.cd_data_init:
            # Mix: half from data+noise (local structure), half from buffer (global gradient).
            n_data = batch_size // 2
            n_buffer = batch_size - n_data
            data_init = x0[:n_data].detach() + self.cd_noise_std * torch.randn(n_data, dim, device=device)
            buffer_init = self._sample_from_buffer(n_buffer, device, dim)
            x_neg_init = torch.cat([data_init, buffer_init], dim=0)
        else:
            x_neg_init = self._sample_from_buffer(batch_size, device, dim)
        x_neg = self._langevin_mcmc(model, x_neg_init, self.cd_steps, self.cd_step_size,
                                    noise_scale_mult=self.cd_noise_scale)

        # Update replay buffer (useful even with data init for monitoring)
        self._update_buffer(x_neg)

        # Energy on negatives (detached — no backprop through MCMC)
        energy_neg = model(x_neg.detach())

        # Contrastive divergence loss
        cd_loss = energy_real.mean() - energy_neg.mean()

        # Energy regularization (prevents energy magnitudes from diverging)
        reg_loss = self.energy_reg * (energy_real ** 2 + energy_neg ** 2).mean()

        return cd_loss + reg_loss

    def sample(
        self,
        model: nn.Module,
        shape,
        device: torch.device,
        num_steps: Optional[int] = None,
        **kwargs,
    ) -> torch.Tensor:
        """Generate samples via Langevin MCMC.

        Args:
            model: Energy network.
            shape: (num_samples, data_dim).
            device: Device.
            num_steps: Total Langevin steps (overrides default).
        """
        model.eval()
        steps = num_steps if num_steps else self.langevin_steps

        x = torch.randn(shape, device=device)

        # Need gradients for Langevin dynamics even if called under torch.no_grad()
        with torch.enable_grad():
            noise_end = self.langevin_noise_end if self.langevin_anneal else -1.0
            x = self._langevin_mcmc(
                model, x, steps, self.langevin_step_size,
                noise_scale_mult=self.langevin_noise_scale,
                noise_end_mult=noise_end,
            )

        return x
